export const legalCategories = [
  {
    id: "family",
    name: "Oila huquqi",
    icon: "Users",
    description: "Nikoh, ajrashish, aliment va vasiylik masalalari",
  },
  {
    id: "labor",
    name: "Mehnat huquqi",
    icon: "Briefcase",
    description: "Mehnat shartnomasi, ishdan bo'shatish va ta'tillar",
  },
  {
    id: "property",
    name: "Mulkiy huquq",
    icon: "Home",
    description: "Uy-joy, yer va ko'chmas muloqot muammolari",
  },
  {
    id: "business",
    name: "Tadbirkorlik",
    icon: "TrendingUp",
    description: "Biznesni ro'yxatdan o'tkazish, soliq va litsenziyalar",
  },
];

export const ADVOCACY_DATA = [
  // FARG'ONA SHAHRI (1-30)
  {
    id: 1,
    name: "Farg'ona Viloyat Advokatlar Palatasi Hududiy Boshqarmasi",
    type: "Boshqarma",
    city: "Farg'ona",
    address: "Farg'ona sh., B.Marg'iloniy ko'chasi, 45-uy",
    phone: "+998 73 244-12-34",
    lat: 40.3864,
    lng: 71.7864,
    description:
      "Viloyat bo'yicha advokatlik faoliyatini muvofiqlashtiruvchi markaziy organ.",
  },
  {
    id: 2,
    name: "Adolat va Qonun Advokatlik Firmasi",
    type: "Advokatlik Firmasi",
    city: "Farg'ona",
    address: "Farg'ona sh., Al-Farg'oniy ko'chasi, 12-uy",
    phone: "+998 90 530-11-22",
    lat: 40.3845,
    lng: 71.7812,
    description:
      "Fuqarolik, jinoyat hamda iqtisodiy ishlar bo'yicha yuridik xizmatlar.",
  },
  {
    id: 3,
    name: "Farg'ona Biznes Huquq Ixtisoslashgan Kollegiyasi",
    type: "Advokatlar Kollegiyasi",
    city: "Farg'ona",
    address: "Farg'ona sh., Sayilgoh ko'chasi, 8-A uy",
    phone: "+998 90 123-45-67",
    lat: 40.3889,
    lng: 71.782,
    description: "Korporativ huquq, soliq va biznesni huquqiy himoyalash.",
  },
  {
    id: 4,
    name: "Lex Protego Advokatlik Byurosi",
    type: "Advokatlik Byurosi",
    city: "Farg'ona",
    address: "Farg'ona sh., Muqimiy ko'chasi, 15-uy",
    phone: "+998 91 201-44-55",
    lat: 40.3821,
    lng: 71.779,
    description: "Soliq va bojxona nizolari bo'yicha maslahatlar.",
  },
  {
    id: 5,
    name: "Farg'ona Himoya Advokatlar Hay'ati",
    type: "Advokatlar Hay'ati",
    city: "Farg'ona",
    address: "Farg'ona sh., B.Marg'iloniy ko'chasi, 102-uy",
    phone: "+998 73 222-30-40",
    lat: 40.3878,
    lng: 71.7895,
    description:
      "Fuqarolik va jinoyat ishlari bo'yicha kompleks davlat va xususiy himoya.",
  },
  {
    id: 6,
    name: "Femida Farg'ona Advokatlik Byurosi",
    type: "Advokatlik Byurosi",
    city: "Farg'ona",
    address: "Farg'ona sh., Qashqar ko'chasi, 4-uy",
    phone: "+998 93 971-88-99",
    lat: 40.381,
    lng: 71.7845,
    description: "Oila va nikoh nizolari, mol-mulkni bo'lish masalalari.",
  },
  {
    id: 7,
    name: "Inamov va Hamkorlar Advokatlik Firmasi",
    type: "Advokatlik Firmasi",
    city: "Farg'ona",
    address: "Farg'ona sh., Navoiy ko'chasi, 28-uy",
    phone: "+998 90 300-12-12",
    lat: 40.3855,
    lng: 71.7833,
    description: "Bank va moliya huquqi, kredit nizolari.",
  },
  {
    id: 8,
    name: "Kafolat-Servis Advokatlik Byurosi",
    type: "Advokatlik Byurosi",
    city: "Farg'ona",
    address: "Farg'ona sh., Tarona ko'chasi, 3-uy",
    phone: "+998 91 112-23-34",
    lat: 40.3892,
    lng: 71.7801,
    description: "Avtomobil va YTH nizolari, sug'urta tovonlarini undirish.",
  },
  {
    id: 9,
    name: "Farg'ona Adolat Qalqoni Byurosi",
    type: "Advokatlik Byurosi",
    city: "Farg'ona",
    address: "Farg'ona sh., Yormazor ko'chasi, 67-uy",
    phone: "+998 94 440-55-66",
    lat: 40.375,
    lng: 71.792,
    description: "Ma'muriy huquqbuzarliklar bo'yicha advokatlik ko'mayi.",
  },
  {
    id: 10,
    name: "Iqtisod va Huquq Advokatlar Kollegiyasi",
    type: "Advokatlar Kollegiyasi",
    city: "Farg'ona",
    address: "Farg'ona sh., Marhamat ko'chasi, 19-uy",
    phone: "+998 73 244-88-11",
    lat: 40.383,
    lng: 71.7755,
    description: "Tadbirkorlik va arbitraj sudlaridagi vakillik.",
  },
  {
    id: 11,
    name: "Huquqiy Ustuvorlik Advokatlik Firmasi",
    type: "Advokatlik Firmasi",
    city: "Farg'ona",
    address: "Farg'ona sh., Aeroport ko'chasi, 5-uy",
    phone: "+998 90 633-99-00",
    lat: 40.364,
    lng: 71.745,
    description: "Xalqaro va intellektual mulk huquqi.",
  },
  {
    id: 12,
    name: "Siddiqov va Advokatlar Byurosi",
    type: "Advokatlik Byurosi",
    city: "Farg'ona",
    address: "Farg'ona sh., Mustaqillik ko'chasi, 14-uy",
    phone: "+998 91 670-22-11",
    lat: 40.386,
    lng: 71.785,
    description: "Meros va yer nizolari bo'yicha mutaxassislar.",
  },
  {
    id: 13,
    name: "Farg'ona Legal Partner Byurosi",
    type: "Advokatlik Byurosi",
    city: "Farg'ona",
    address: "Farg'ona sh., Chekhov ko'chasi, 2-uy",
    phone: "+998 93 730-40-50",
    lat: 40.3871,
    lng: 71.7815,
    description: "Shartnomalarni audit qilish va yuridik kuzatuv.",
  },
  {
    id: 14,
    name: "Vatan Huquqiy Himoya Byurosi",
    type: "Advokatlik Byurosi",
    city: "Farg'ona",
    address: "Farg'ona sh., S.Temur ko'chasi, 88-uy",
    phone: "+998 90 580-11-00",
    lat: 40.3801,
    lng: 71.7888,
    description: "Mehnat nizolari va kadrlar masalalari.",
  },
  {
    id: 15,
    name: "Akkreditativ Advokatlik Firmasi",
    type: "Advokatlik Firmasi",
    city: "Farg'ona",
    address: "Farg'ona sh., Kosmonavtlar ko'chasi, 11-uy",
    phone: "+998 94 100-20-30",
    lat: 40.3899,
    lng: 71.777,
    description:
      "Investitsiya va chet el kapitali ishtirokidagi korxonalar himoyasi.",
  },
  {
    id: 16,
    name: "Haqiqat va Adolat Byurosi",
    type: "Advokatlik Byurosi",
    city: "Farg'ona",
    address: "Farg'ona sh., Sharq ko'chasi, 41-uy",
    phone: "+998 91 280-99-88",
    lat: 40.384,
    lng: 71.789,
    description: "Fuqarolik sudlarida apellyatsiya va kassatsiya shikoyatlari.",
  },
  {
    id: 17,
    name: "Pro Yuris Advokatlar Hay'ati",
    type: "Advokatlar Hay'ati",
    city: "Farg'ona",
    address: "Farg'ona sh., Farg'ona ko'chasi, 120-uy",
    phone: "+998 73 224-55-66",
    lat: 40.3818,
    lng: 71.7831,
    description: "Iqtisodiy jinoyatlar bo'yicha ixtisoslashgan himoya.",
  },
  {
    id: 18,
    name: "Yurist Konsultant Byurosi",
    type: "Advokatlik Byurosi",
    city: "Farg'ona",
    address: "Farg'ona sh., Guliston ko'chasi, 9-uy",
    phone: "+998 90 292-88-77",
    lat: 40.3882,
    lng: 71.7844,
    description: "Aholiga bepul dastlabki huquqiy maslahat berish.",
  },
  {
    id: 19,
    name: "Farg'ona Konsalt Intex Byurosi",
    type: "Advokatlik Byurosi",
    city: "Farg'ona",
    address: "Farg'ona sh., Oybek ko'chasi, 33-uy",
    phone: "+998 93 480-12-34",
    lat: 40.3835,
    lng: 71.7788,
    description: "Qurilish va ko'chmas mulk nizolari.",
  },
  {
    id: 20,
    name: "Tadbirkor Qalqoni Firmasi",
    type: "Advokatlik Firmasi",
    city: "Farg'ona",
    address: "Farg'ona sh., Sanoat ko'chasi, 18-uy",
    phone: "+998 91 120-33-44",
    lat: 40.3711,
    lng: 71.801,
    description:
      "Kichik va o'rta biznes vakillarini huquqiy qo'llab-quvvatlash.",
  },
  {
    id: 21,
    name: "Ziyo Advokatlik Byurosi",
    type: "Advokatlik Byurosi",
    city: "Farg'ona",
    address: "Farg'ona sh., Nodira ko'chasi, 7-uy",
    phone: "+998 90 405-66-77",
    lat: 40.3868,
    lng: 71.7825,
    description: "Mualliflik huquqi va litsenziyalash nizolari.",
  },
  {
    id: 22,
    name: "Farg'ona Alfa Legis Byurosi",
    type: "Advokatlik Byurosi",
    city: "Farg'ona",
    address: "Farg'ona sh., Pushkin ko'chasi, 21-uy",
    phone: "+998 94 330-77-11",
    lat: 40.3851,
    lng: 71.7808,
    description:
      "Jinoyat ishlari bo'yicha sudgacha bo'lgan surishtiruvda himoya.",
  },
  {
    id: 23,
    name: "Qonuniylik va Adolat Firmasi",
    type: "Advokatlik Firmasi",
    city: "Farg'ona",
    address: "Farg'ona sh., Lermontov ko'chasi, 5-uy",
    phone: "+998 91 690-00-11",
    lat: 40.3875,
    lng: 71.786,
    description: "Uy-joy ko'chirish va mulk huquqini tiklash.",
  },
  {
    id: 24,
    name: "Garant Yuris Byurosi",
    type: "Advokatlik Byurosi",
    city: "Farg'ona",
    address: "Farg'ona sh., Drujba ko'chasi, 16-uy",
    phone: "+998 90 144-55-66",
    lat: 40.3838,
    lng: 71.788,
    description: "Qarz undirish va Majburiy ijro bo'yicha masalalar.",
  },
  {
    id: 25,
    name: "O'zbekiston Huquqshunoslar Byurosi",
    type: "Advokatlik Byurosi",
    city: "Farg'ona",
    address: "Farg'ona sh., Bobur ko'chasi, 40-uy",
    phone: "+998 93 200-88-99",
    lat: 40.3828,
    lng: 71.7839,
    description: "Fuqarolik holati dalolatnomalari va fuqarolikni aniqlash.",
  },
  {
    id: 26,
    name: "Advokat-Ekspert Firmasi",
    type: "Advokatlik Firmasi",
    city: "Farg'ona",
    address: "Farg'ona sh., Marg'iloniy ko'chasi, 12-A uy",
    phone: "+998 73 244-01-02",
    lat: 40.3861,
    lng: 71.7871,
    description:
      "Ekspertizalar tayinlash va ekspert xulosalariga e'tiroz bildirish.",
  },
  {
    id: 27,
    name: "Farg'ona Inter-Lex Byurosi",
    type: "Advokatlik Byurosi",
    city: "Farg'ona",
    address: "Farg'ona sh., Hamza ko'chasi, 55-uy",
    phone: "+998 90 777-11-22",
    lat: 40.3812,
    lng: 71.7802,
    description: "Chet el fuqarolarining O'zbekistondagi huquqiy himoyasi.",
  },
  {
    id: 28,
    name: "Nizolarni Hal Etish Markazi Byurosi",
    type: "Advokatlik Byurosi",
    city: "Farg'ona",
    address: "Farg'ona sh., Toshkent ko'chasi, 72-uy",
    phone: "+998 91 333-44-55",
    lat: 40.389,
    lng: 71.7855,
    description:
      "Mediatsiya va sudgacha nizolarni tinch yo'l bilan hal qilish.",
  },
  {
    id: 29,
    name: "Nodirbek va Hamkorlar Byurosi",
    type: "Advokatlik Byurosi",
    city: "Farg'ona",
    address: "Farg'ona sh., Shiroq ko'chasi, 3-uy",
    phone: "+998 94 620-11-33",
    lat: 40.3847,
    lng: 71.7818,
    description: "Sug'urta va bank kafolatlari bo'yicha advokatlik.",
  },
  {
    id: 30,
    name: "Farg'ona Status Legis Byurosi",
    type: "Advokatlik Byurosi",
    city: "Farg'ona",
    address: "Farg'ona sh., Furqat ko'chasi, 19-uy",
    phone: "+998 90 999-00-11",
    lat: 40.3866,
    lng: 71.783,
    description:
      "Ma'muriy sudlarda davlat organlari qarorlari ustidan shikoyat.",
  },

  // MARG'ILON SHAHRI (31-50)
  {
    id: 31,
    name: "Marg'ilon Himoya Advokatlik Byurosi",
    type: "Advokatlik Byurosi",
    city: "Marg'ilon",
    address: "Marg'ilon sh., Mustaqillik ko'chasi, 78-uy",
    phone: "+998 91 680-33-44",
    lat: 40.4721,
    lng: 71.7133,
    description: "Ixtisoslashtirilgan fuqarolik va oila huquqi masalalari.",
  },
  {
    id: 32,
    name: "Marg'ilon Adolat Markazi Byurosi",
    type: "Advokatlik Byurosi",
    city: "Marg'ilon",
    address: "Marg'ilon sh., B.Marg'iloniy ko'chasi, 110-uy",
    phone: "+998 73 234-11-22",
    lat: 40.475,
    lng: 71.718,
    description: "Tadbirkorlik va xususiy mulk bo'yicha sud vakilligi.",
  },
  {
    id: 33,
    name: "Ipak Yuli Huquqshunoslari Firmasi",
    type: "Advokatlik Firmasi",
    city: "Marg'ilon",
    address: "Marg'ilon sh., Ahmad Yassaviy ko'chasi, 15-uy",
    phone: "+998 90 200-44-55",
    lat: 40.4705,
    lng: 71.7101,
    description: "Tijorat va savdo shartnomalari huquqiy tahlili.",
  },
  {
    id: 34,
    name: "Marg'ilon Advokatlar Hay'ati",
    type: "Advokatlar Hay'ati",
    city: "Marg'ilon",
    address: "Marg'ilon sh., Turkiston ko'chasi, 42-uy",
    phone: "+998 93 370-11-00",
    lat: 40.4733,
    lng: 71.7155,
    description: "Jinoyat va fuqarolik ishlari bo'yicha malakali himoya.",
  },
  {
    id: 35,
    name: "Burhoniddin Marg'inoniy Legis Byurosi",
    type: "Advokatlik Byurosi",
    city: "Marg'ilon",
    address: "Marg'ilon sh., S.Sheroziy ko'chasi, 5-uy",
    phone: "+998 91 155-22-33",
    lat: 40.4712,
    lng: 71.712,
    description: "Meros taqsimoti va vasiylik masalalari.",
  },
  {
    id: 36,
    name: "Marg'ilon Konsalt Yuris Byurosi",
    type: "Advokatlik Byurosi",
    city: "Marg'ilon",
    address: "Marg'ilon sh., Navoiy ko'chasi, 89-uy",
    phone: "+998 94 500-66-77",
    lat: 40.476,
    lng: 71.72,
    description: "Ko'chmas mulk oldi-sotdisi huquqiy xavfsizligi.",
  },
  {
    id: 37,
    name: "Atlas-Legal Advokatlik Firmasi",
    type: "Advokatlik Firmasi",
    city: "Marg'ilon",
    address: "Marg'ilon sh., Shohrud ko'chasi, 23-uy",
    phone: "+998 90 600-88-99",
    lat: 40.469,
    lng: 71.708,
    description:
      "To'qimachilik va hunarmandchilik sub'ektlariga yuridik xizmat.",
  },
  {
    id: 38,
    name: "Marg'ilon Qalqon Byurosi",
    type: "Advokatlik Byurosi",
    city: "Marg'ilon",
    address: "Marg'ilon sh., Tinchlik ko'chasi, 12-uy",
    phone: "+998 93 680-00-11",
    lat: 40.4741,
    lng: 71.7144,
    description: "Soliq tekshiruvlarida advokatlik ishtiroki.",
  },
  {
    id: 39,
    name: "Saydaliyev va Hamkorlar Byurosi",
    type: "Advokatlik Byurosi",
    city: "Marg'ilon",
    address: "Marg'ilon sh., Usmon Nosir ko'chasi, 3-uy",
    phone: "+998 91 222-11-00",
    lat: 40.4728,
    lng: 71.7166,
    description: "Aholining ijtimoiy himoyaga muhtoj qatlamiga yuridik yordam.",
  },
  {
    id: 40,
    name: "Marg'ilon Ishonch Legis Byurosi",
    type: "Advokatlik Byurosi",
    city: "Marg'ilon",
    address: "Marg'ilon sh., Feruza ko'chasi, 67-uy",
    phone: "+998 90 333-22-11",
    lat: 40.4771,
    lng: 71.7192,
    description: "Oila va aliment undirish nizolari.",
  },
  {
    id: 41,
    name: "Marg'ilon Adolat Nur Byurosi",
    type: "Advokatlik Byurosi",
    city: "Marg'ilon",
    address: "Marg'ilon sh., Chilonzor ko'chasi, 8-uy",
    phone: "+998 94 111-00-22",
    lat: 40.468,
    lng: 71.705,
    description: "Yer uchastkalariga bo'lgan huquqlarni tiklash.",
  },
  {
    id: 42,
    name: "Marg'ilon Huquq Standart Firmasi",
    type: "Advokatlik Firmasi",
    city: "Marg'ilon",
    address: "Marg'ilon sh., O'zbekiston ko'chasi, 101-uy",
    phone: "+998 73 235-44-55",
    lat: 40.4739,
    lng: 71.713,
    description: "Tadbirkorlik faoliyatini litsenziyalash va ruxsatnomalar.",
  },
  {
    id: 43,
    name: "Zahiriddin Bobur Byurosi",
    type: "Advokatlik Byurosi",
    city: "Marg'ilon",
    address: "Marg'ilon sh., Bobur ko'chasi, 14-uy",
    phone: "+998 90 700-55-44",
    lat: 40.4719,
    lng: 71.7111,
    description: "Mehnat huquqlari va noqonuniy bo'shatish bo'yicha davolar.",
  },
  {
    id: 44,
    name: "Marg'ilon Ekspert Yuris Byurosi",
    type: "Advokatlik Byurosi",
    city: "Marg'ilon",
    address: "Marg'ilon sh., Zarafshon ko'chasi, 33-uy",
    phone: "+998 91 400-33-22",
    lat: 40.4755,
    lng: 71.7177,
    description: "Iqtisodiy sudlarda vakillik va da'vo arizalari.",
  },
  {
    id: 45,
    name: "Marg'ilon Vektor Advokatlik Firmasi",
    type: "Advokatlik Firmasi",
    city: "Marg'ilon",
    address: "Marg'ilon sh., Yangi hayot ko'chasi, 2-uy",
    phone: "+998 93 900-11-22",
    lat: 40.4699,
    lng: 71.7099,
    description: "Korporativ tuzilmalarni qayta tashkil etish va tugatish.",
  },
  {
    id: 46,
    name: "Marg'ilon Lex-Service Byurosi",
    type: "Advokatlik Byurosi",
    city: "Marg'ilon",
    address: "Marg'ilon sh., Furqat ko'chasi, 51-uy",
    phone: "+998 94 600-44-33",
    lat: 40.4748,
    lng: 71.715,
    description: "Ma'muriy jarimalar va qarorlar ustidan shikoyat.",
  },
  {
    id: 47,
    name: "Marg'ilon Kafolat Yuris Byurosi",
    type: "Advokatlik Byurosi",
    city: "Marg'ilon",
    address: "Marg'ilon sh., Kosmonavtlar ko'chasi, 9-uy",
    phone: "+998 90 222-33-44",
    lat: 40.471,
    lng: 71.7125,
    description: "Bank kredit shartnomalarini ekspertiza qilish.",
  },
  {
    id: 48,
    name: "Marg'ilon Konsultant Pro Byurosi",
    type: "Advokatlik Byurosi",
    city: "Marg'ilon",
    address: "Marg'ilon sh., Dehqon ko'chasi, 18-uy",
    phone: "+998 91 888-00-11",
    lat: 40.4765,
    lng: 71.7188,
    description: "Bojxona va eksport-import operatsiyalari.",
  },
  {
    id: 49,
    name: "Marg'ilon Sheriklar Advokatlik Firmasi",
    type: "Advokatlik Firmasi",
    city: "Marg'ilon",
    address: "Marg'ilon sh., Bog'idon ko'chasi, 4-uy",
    phone: "+998 93 111-22-33",
    lat: 40.47,
    lng: 71.7075,
    description: "Tijorat bitimlarini huquqiy rasmiylashtirish.",
  },
  {
    id: 50,
    name: "Marg'ilon Huquqiy Madad Byurosi",
    type: "Advokatlik Byurosi",
    city: "Marg'ilon",
    address: "Marg'ilon sh., Sabzavot ko'chasi, 29-uy",
    phone: "+998 90 555-66-77",
    lat: 40.473,
    lng: 71.714,
    description: "Fuqarolarga har tomonlama huquqiy yordam.",
  },

  // QO'QON SHAHRI (51-70)
  {
    id: 51,
    name: "Qo'qon Huquqiy Madad Advokatlar Hay'ati",
    type: "Advokatlar Hay'ati",
    city: "Qo'qon",
    address: "Qo'qon sh., Me'morlar ko'chasi, 15-uy",
    phone: "+998 73 542-00-11",
    lat: 40.5283,
    lng: 70.9425,
    description:
      "Tadbirkorlik va iqtisodiy nizolar bo'yicha advokatlik ko'mayi.",
  },
  {
    id: 52,
    name: "Qo'qon Ekspert Advokatlik Byurosi",
    type: "Advokatlik Byurosi",
    city: "Qo'qon",
    address: "Qo'qon sh., Usmon Nosir ko'chasi, 44-uy",
    phone: "+998 73 541-22-33",
    lat: 40.531,
    lng: 70.938,
    description: "Shartnomaviy va fuqarolik munosabatlari.",
  },
  {
    id: 53,
    name: "Xudoyorxon Legis Advokatlik Firmasi",
    type: "Advokatlik Firmasi",
    city: "Qo'qon",
    address: "Qo'qon sh., Istiklol ko'chasi, 2-uy",
    phone: "+998 90 560-77-88",
    lat: 40.5295,
    lng: 70.941,
    description: "Tijorat sub'ektlari o'rtasidagi moliyaviy nizolar.",
  },
  {
    id: 54,
    name: "Qo'qon Adolat Qalqoni Byurosi",
    type: "Advokatlik Byurosi",
    city: "Qo'qon",
    address: "Qo'qon sh., Turon ko'chasi, 89-uy",
    phone: "+998 91 690-33-22",
    lat: 40.527,
    lng: 70.945,
    description: "Jinoyat ishlari bo'yicha himoyachi advokatlar.",
  },
  {
    id: 55,
    name: "Qo'qon Biznes Yuris Kollegiyasi",
    type: "Advokatlar Kollegiyasi",
    city: "Qo'qon",
    address: "Qo'qon sh., Farg'ona yo'li ko'chasi, 12-uy",
    phone: "+998 73 543-88-99",
    lat: 40.534,
    lng: 70.95,
    description: "Katta hachmdagi iqtisodiy va bank davolari.",
  },
  {
    id: 56,
    name: "Qo'qon Himoyachi Byurosi",
    type: "Advokatlik Byurosi",
    city: "Qo'qon",
    address: "Qo'qon sh., Navoiy ko'chasi, 31-uy",
    phone: "+998 93 970-11-22",
    lat: 40.526,
    lng: 70.939,
    description: "Oila va aliment huquqlari bo'yicha mutaxassis.",
  },
  {
    id: 57,
    name: "Qo'qon Lex-Group Firmasi",
    type: "Advokatlik Firmasi",
    city: "Qo'qon",
    address: "Qo'qon sh., Muqimiy ko'chasi, 7-uy",
    phone: "+998 90 300-88-11",
    lat: 40.5301,
    lng: 70.9433,
    description: "Ko'chmas mulk va qurilish nizolari.",
  },
  {
    id: 58,
    name: "Qo'qon Ishonch Advokatlik Byurosi",
    type: "Advokatlik Byurosi",
    city: "Qo'qon",
    address: "Qo'qon sh., Saodat ko'chasi, 55-uy",
    phone: "+998 91 123-99-88",
    lat: 40.5325,
    lng: 70.9365,
    description: "Meros va vasiylik shartnomalari.",
  },
  {
    id: 59,
    name: "Farovon Huquq Qo'qon Byurosi",
    type: "Advokatlik Byurosi",
    city: "Qo'qon",
    address: "Qo'qon sh., Lutfiy ko'chasi, 18-uy",
    phone: "+998 94 400-22-11",
    lat: 40.5255,
    lng: 70.9405,
    description: "Mehnat nizolari bo'yicha kompensatsiya undirish.",
  },
  {
    id: 60,
    name: "Qo'qon Konsalt Yuris Byurosi",
    type: "Advokatlik Byurosi",
    city: "Qo'qon",
    address: "Qo'qon sh., Charxiy ko'chasi, 3-uy",
    phone: "+998 90 600-11-00",
    lat: 40.5288,
    lng: 70.947,
    description: "Soliq to'lovchilarning huquqlarini himoya qilish.",
  },
  {
    id: 61,
    name: "Qo'qon Garant Legis Byurosi",
    type: "Advokatlik Byurosi",
    city: "Qo'qon",
    address: "Qo'qon sh., Hamza ko'chasi, 62-uy",
    phone: "+998 93 222-00-11",
    lat: 40.5318,
    lng: 70.9398,
    description: "YTH va transport hodisalari bo'yicha legal yordam.",
  },
  {
    id: 62,
    name: "Qo'qon Ziyo Advokatlar Hay'ati",
    type: "Advokatlar Hay'ati",
    city: "Qo'qon",
    address: "Qo'qon sh., Bobur ko'chasi, 102-uy",
    phone: "+998 73 541-90-90",
    lat: 40.5277,
    lng: 70.9444,
    description: "Fuqarolik va jinoyat protsessual vakilligi.",
  },
  {
    id: 63,
    name: "Qo'qon Insaft Advokatlik Byurosi",
    type: "Advokatlik Byurosi",
    city: "Qo'qon",
    address: "Qo'qon sh., G'ozio'g'li ko'chasi, 21-uy",
    phone: "+998 91 888-33-22",
    lat: 40.529,
    lng: 70.9372,
    description: "Ma'muriy sudlov ishlari va arizalar tayyorlash.",
  },
  {
    id: 64,
    name: "Qo'qon Trade Legal Firmasi",
    type: "Advokatlik Firmasi",
    city: "Qo'qon",
    address: "Qo'qon sh., Bozor ko'chasi, 5-uy",
    phone: "+998 90 100-55-66",
    lat: 40.5333,
    lng: 70.9415,
    description: "Ulgurji va chakana savdo sub'ektlarini himoya qilish.",
  },
  {
    id: 65,
    name: "Qo'qon Boshpanam Byurosi",
    type: "Advokatlik Byurosi",
    city: "Qo'qon",
    address: "Qo'qon sh., Yangibog' ko'chasi, 40-uy",
    phone: "+998 94 300-11-44",
    lat: 40.5248,
    lng: 70.9429,
    description: "Uy-joyga egalik huquqini belgilash.",
  },
  {
    id: 66,
    name: "Qo'qon status-Yuris Byurosi",
    type: "Advokatlik Byurosi",
    city: "Qo'qon",
    address: "Qo'qon sh., S. Sheroziy ko'chasi, 19-uy",
    phone: "+998 93 777-88-99",
    lat: 40.5305,
    lng: 70.9461,
    description: "Intellektual va brend mulkini hisobga qo'yish nizolari.",
  },
  {
    id: 67,
    name: "Qo'qon Vektor Legis Byurosi",
    type: "Advokatlik Byurosi",
    city: "Qo'qon",
    address: "Qo'qon sh., Furqat ko'chasi, 77-uy",
    phone: "+998 90 220-44-55",
    lat: 40.5268,
    lng: 70.9388,
    description: "Shartnoma shartlarini majburiy bajarish bo'yicha da'volar.",
  },
  {
    id: 68,
    name: "Qo'qon Inter-Consult Firmasi",
    type: "Advokatlik Firmasi",
    city: "Qo'qon",
    address: "Qo'qon sh., Temiryo'l ko'chasi, 11-uy",
    phone: "+998 73 542-33-22",
    lat: 40.535,
    lng: 70.9488,
    description: "Transport va logistika korxonalari yuridik kuzatuvi.",
  },
  {
    id: 69,
    name: "Qo'qon Madad Yuris Byurosi",
    type: "Advokatlik Byurosi",
    city: "Qo'qon",
    address: "Qo'qon sh., Katta Xiyobon ko'chasi, 8-uy",
    phone: "+998 91 500-11-22",
    lat: 40.528,
    lng: 70.94,
    description: "Aholi murojaatlari va shikoyatlarini tayyorlash.",
  },
  {
    id: 70,
    name: "Qo'qon Standard Legal Byurosi",
    type: "Advokatlik Byurosi",
    city: "Qo'qon",
    address: "Qo'qon sh., Nodira ko'chasi, 33-uy",
    phone: "+998 94 200-99-88",
    lat: 40.5298,
    lng: 70.9439,
    description: "Davlat va nodavlat tashkilotlarda vakillik.",
  },

  // OLTIARIQ VA RISHTON TUMANLARI (71-85)
  {
    id: 71,
    name: "Oltiariq Konsalt Advokatlik Byurosi",
    type: "Advokatlik Byurosi",
    city: "Oltiariq",
    address: "Oltiariq t., Markaziy ko'cha, 5-uy",
    phone: "+998 93 970-55-66",
    lat: 40.3956,
    lng: 71.4789,
    description: "Mulk va yer huquqi bo'yicha maslahat va sud vakilligi.",
  },
  {
    id: 72,
    name: "Oltiariq Adolat Advokatlik Byurosi",
    type: "Advokatlik Byurosi",
    city: "Oltiariq",
    address: "Oltiariq t., Mustaqillik ko'chasi, 18-uy",
    phone: "+998 90 533-22-11",
    lat: 40.397,
    lng: 71.481,
    description: "Fermer xo'jaliklari va agrosektor huquqiy himoyasi.",
  },
  {
    id: 73,
    name: "Oltiariq Himoya Byurosi",
    type: "Advokatlik Byurosi",
    city: "Oltiariq",
    address: "Oltiariq t., Sharq ko'chasi, 2-uy",
    phone: "+998 91 677-88-99",
    lat: 40.394,
    lng: 71.476,
    description: "Fuqarolik va jinoyat ishlari bo'yicha advokatlik.",
  },
  {
    id: 74,
    name: "Oltiariq Yuris-Servis Firmasi",
    type: "Advokatlik Firmasi",
    city: "Oltiariq",
    address: "Oltiariq t., B.Marg'iloniy ko'chasi, 40-uy",
    phone: "+998 73 432-10-20",
    lat: 40.3962,
    lng: 71.48,
    description: "Kredit nizolari va uy-joy masalalari.",
  },
  {
    id: 75,
    name: "Oltiariq Qalqon Legis Byurosi",
    type: "Advokatlik Byurosi",
    city: "Oltiariq",
    address: "Oltiariq t., Uzumzor ko'chasi, 11-uy",
    phone: "+998 94 105-44-33",
    lat: 40.3985,
    lng: 71.483,
    description: "Oila va aliment da'volari.",
  },
  {
    id: 76,
    name: "Rishton Advokatlik Tuzilmasi",
    type: "Advokatlik Byurosi",
    city: "Rishton",
    address: "Rishton sh., Amir Temur ko'chasi, 22-uy",
    phone: "+998 90 290-77-88",
    lat: 40.3562,
    lng: 71.2841,
    description:
      "Aholi va yuridik shaxslarga barcha turdagi huquqiy xizmatlar.",
  },
  {
    id: 77,
    name: "Rishton Adolat Qalqoni Byurosi",
    type: "Advokatlik Byurosi",
    city: "Rishton",
    address: "Rishton sh., Farg'ona ko'chasi, 50-uy",
    phone: "+998 91 200-11-22",
    lat: 40.358,
    lng: 71.287,
    description: "Kulolchilik va hunarmandchilik sub'ektlariga ko'mak.",
  },
  {
    id: 78,
    name: "Rishton Himoyachi Byurosi",
    type: "Advokatlik Byurosi",
    city: "Rishton",
    address: "Rishton sh., Chinniyashlar ko'chasi, 8-uy",
    phone: "+998 93 300-44-55",
    lat: 40.3545,
    lng: 71.282,
    description: "Jinoyat ishlari bo'yicha dastlabki tergovda himoya.",
  },
  {
    id: 79,
    name: "Rishton Konsalt Yuris Firmasi",
    type: "Advokatlik Firmasi",
    city: "Rishton",
    address: "Rishton sh., Navoiy ko'chasi, 101-uy",
    phone: "+998 73 452-11-00",
    lat: 40.3571,
    lng: 71.2855,
    description: "Yer uchastkalari va meros huquqi.",
  },
  {
    id: 80,
    name: "Rishton Ishonch Legis Byurosi",
    type: "Advokatlik Byurosi",
    city: "Rishton",
    address: "Rishton sh., Dehqon ko'chasi, 3-uy",
    phone: "+998 94 600-88-77",
    lat: 40.355,
    lng: 71.2833,
    description: "Ma'muriy nizolar va xususiy mol-mulk daxlsizligi.",
  },
  {
    id: 81,
    name: "Oltiariq Ziyo Legal Byurosi",
    type: "Advokatlik Byurosi",
    city: "Oltiariq",
    address: "Oltiariq t., Bog'ichinor ko'chasi, 14-uy",
    phone: "+998 90 400-55-11",
    lat: 40.393,
    lng: 71.474,
    description: "Sud ijrochilari harakatlari ustidan shikoyat tayyorlash.",
  },
  {
    id: 82,
    name: "Oltiariq Ekspert Yuris Byurosi",
    type: "Advokatlik Byurosi",
    city: "Oltiariq",
    address: "Oltiariq t., Tinchlik ko'chasi, 89-uy",
    phone: "+998 91 100-22-33",
    lat: 40.398,
    lng: 71.482,
    description: "Fuqarolik sudlarida xususiy advokatlik vakilligi.",
  },
  {
    id: 83,
    name: "Rishton Madad Legis Byurosi",
    type: "Advokatlik Byurosi",
    city: "Rishton",
    address: "Rishton sh., Mustaqillik ko'chasi, 45-uy",
    phone: "+998 93 888-00-99",
    lat: 40.359,
    lng: 71.289,
    description: "Mehnat nizolari va kompensatsiyalar undiruvi.",
  },
  {
    id: 84,
    name: "Rishton Status Yuris Byurosi",
    type: "Advokatlik Byurosi",
    city: "Rishton",
    address: "Rishton sh., Ibn Sino ko'chasi, 12-uy",
    phone: "+998 90 777-33-44",
    lat: 40.3533,
    lng: 71.2805,
    description: "Tadbirkorlik faoliyatida shartnomaviy tahlil.",
  },
  {
    id: 85,
    name: "Oltiariq Boshpanam Byurosi",
    type: "Advokatlik Byurosi",
    city: "Oltiariq",
    address: "Oltiariq t., Yangiobod ko'chasi, 27-uy",
    phone: "+998 94 222-11-00",
    lat: 40.3948,
    lng: 71.4775,
    description: "Uy-joy mulkdorlari huquqlarini belgilash.",
  },

  // QUVASOY, BAG'DOD VA BOSHQA TUMANLAR (86-100)
  {
    id: 86,
    name: "Quvasoy Legal Protection Advokatlik Firmasi",
    type: "Advokatlik Firmasi",
    city: "Quvasoy",
    address: "Quvasoy sh., Tinchlik ko'chasi, 3-uy",
    phone: "+998 73 372-15-15",
    lat: 40.3015,
    lng: 71.9782,
    description: "Mehnat nizolari va ma'muriy ishlar bo'yicha advokatlar.",
  },
  {
    id: 87,
    name: "Quvasoy Adolat Byurosi",
    type: "Advokatlik Byurosi",
    city: "Quvasoy",
    address: "Quvasoy sh., Do'stlik ko'chasi, 19-uy",
    phone: "+998 90 330-11-22",
    lat: 40.303,
    lng: 71.98,
    description: "Sanoat va korxona xodimlari uchun yuridik maslahat.",
  },
  {
    id: 88,
    name: "Quvasoy Himoyachi Legis Byurosi",
    type: "Advokatlik Byurosi",
    city: "Quvasoy",
    address: "Quvasoy sh., Mustaqillik ko'chasi, 44-uy",
    phone: "+998 91 150-44-55",
    lat: 40.299,
    lng: 71.975,
    description: "Fuqarolik va jinoyat bo'yicha sud vakilligi.",
  },
  {
    id: 89,
    name: "Bag'dod Qalqon Advokatlik Byurosi",
    type: "Advokatlik Byurosi",
    city: "Bag'dod",
    address: "Bag'dod t., Istiklol ko'chasi, 10-uy",
    phone: "+998 94 555-44-33",
    lat: 40.455,
    lng: 71.2188,
    description: "Jinoyat ishlari bo'yicha himoya va sudda vakillik.",
  },
  {
    id: 90,
    name: "Bag'dod Adolat Yuris Byurosi",
    type: "Advokatlik Byurosi",
    city: "Bag'dod",
    address: "Bag'dod t., Markaziy ko'cha, 2-uy",
    phone: "+998 90 622-00-11",
    lat: 40.4565,
    lng: 71.2205,
    description: "Fermer xo'jaligi nizolari va yer huquqlari.",
  },
  {
    id: 91,
    name: "Bag'dod Ishonch Advokatlik Firmasi",
    type: "Advokatlik Firmasi",
    city: "Bag'dod",
    address: "Bag'dod t., Navoiy ko'chasi, 15-uy",
    phone: "+998 73 442-12-00",
    lat: 40.4535,
    lng: 71.217,
    description: "Oila, aliment va nikoh shartnomalari.",
  },
  {
    id: 92,
    name: "Buvayda Legal Yuris Byurosi",
    type: "Advokatlik Byurosi",
    city: "Buvayda",
    address: "Buvayda t., Ipak yo'li ko'chasi, 88-uy",
    phone: "+998 91 280-33-11",
    lat: 40.59,
    lng: 71.12,
    description: "Tadbirkorlik faoliyatini huquqiy qo'llab-quvvatlash.",
  },
  {
    id: 93,
    name: "Buvayda Himoya Byurosi",
    type: "Advokatlik Byurosi",
    city: "Buvayda",
    address: "Buvayda t., Mustaqillik ko'chasi, 12-uy",
    phone: "+998 93 400-55-66",
    lat: 40.592,
    lng: 71.123,
    description: "Fuqarolik da'volari va sud hujjatlari tayyorlash.",
  },
  {
    id: 94,
    name: "Uchko'prik Adolat Legis Byurosi",
    type: "Advokatlik Byurosi",
    city: "Uchko'prik",
    address: "Uchko'prik t., Farg'ona yo'li ko'chasi, 5-uy",
    phone: "+998 90 111-44-33",
    lat: 40.54,
    lng: 71.05,
    description: "Meros va mol-mulk nizolarini hal etish.",
  },
  {
    id: 95,
    name: "Uchko'prik Yuris Firmasi",
    type: "Advokatlik Firmasi",
    city: "Uchko'prik",
    address: "Uchko'prik t., Navoiy ko'chasi, 34-uy",
    phone: "+998 94 333-88-00",
    lat: 40.542,
    lng: 71.053,
    description: "Tijorat shartnomalarini rasmiylashtirish.",
  },
  {
    id: 96,
    name: "Toshloq Legal Advokatlik Byurosi",
    type: "Advokatlik Byurosi",
    city: "Toshloq",
    address: "Toshloq t., Farg'ona ko'chasi, 101-uy",
    phone: "+998 91 600-22-11",
    lat: 40.52,
    lng: 71.76,
    description: "Xususiy mulk bo'yicha da'volar va vakillik.",
  },
  {
    id: 97,
    name: "Toshloq Adolat Qalqoni Byurosi",
    type: "Advokatlik Byurosi",
    city: "Toshloq",
    address: "Toshloq t., Sharq ko'chasi, 14-uy",
    phone: "+998 93 999-11-00",
    lat: 40.522,
    lng: 71.763,
    description: "Jinoyat va ma'muriy ishlar bo'yicha himoya.",
  },
  {
    id: 98,
    name: "Yozyovon Himoyachi Byurosi",
    type: "Advokatlik Byurosi",
    city: "Yozyovon",
    address: "Yozyovon t., Markaziy ko'cha, 7-uy",
    phone: "+998 90 500-66-55",
    lat: 40.66,
    lng: 71.74,
    description: "Fermerlar va klasterlar bo'yicha yuridik xizmat.",
  },
  {
    id: 99,
    name: "Quva Adolat Yuris Byurosi",
    type: "Advokatlik Byurosi",
    city: "Quva",
    address: "Quva t., Farg'ona ko'chasi, 23-uy",
    phone: "+998 91 300-77-88",
    lat: 40.52,
    lng: 72.07,
    description: "Mulk nizolari, uy-joy va aliment masalalari.",
  },
  {
    id: 100,
    name: "Quva Ekspert Advokatlik Firmasi",
    type: "Advokatlik Firmasi",
    city: "Quva",
    address: "Quva t., S.Temur ko'chasi, 55-uy",
    phone: "+998 73 315-11-22",
    lat: 40.523,
    lng: 72.073,
    description: "Kredit, bank va tijorat nizolari bo'yicha advokatlik.",
  },
];
